# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.IntegerField(choices=[(1, 'Primer Nivel'), (2, 'Segundo Nivel')])),
                ('identidad', models.CharField(max_length=13)),
                ('expediente', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')])),
                ('edad_anios', models.IntegerField()),
                ('edad_meses', models.IntegerField()),
                ('pseudonimo', models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True)),
                ('estado_civil', models.IntegerField(choices=[(1, 'Soltero(a)'), (2, 'Casado(a)'), (3, 'Union Libre')])),
                ('telefono_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('bloque', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('referencias', models.CharField(blank=True, max_length=500, null=True)),
                ('grupo_etnico', models.IntegerField(choices=[(1, 'Mestizo'), (2, 'Misquito'), (3, 'Pech'), (4, 'Maya Chorti'), (5, 'Tawahka'), (6, 'Garifuna'), (7, 'Negro de Habla Inglesa'), (8, 'Lenca'), (9, 'Tolupan'), (1, 'Otro')])),
                ('otro_grupo_etnico', models.CharField(blank=True, max_length=50, null=True)),
                ('identidad_madre', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_madre', models.CharField(blank=True, max_length=10, null=True)),
                ('identidad_padre', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=10, null=True)),
                ('identidad_tutor', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_tutor', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_tutor', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_tutor', models.CharField(blank=True, max_length=500, null=True)),
                ('poblacion', models.IntegerField(blank=True, choices=[(1, 'Poblacion General'), (2, 'HSH'), (3, 'Trabajador(a) Sexual'), (4, 'Transgenero\t')], null=True)),
                ('fecha_ultima_menstruacion', models.CharField(blank=True, max_length=10, null=True)),
                ('rnp', models.NullBooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad_economica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.ActividadesEconomicas')),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por_boleta', to=settings.AUTH_USER_MODEL)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boleta_origen_barrios', to='general.Ciudades')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boleta_origen_ciudades', to='general.Ciudades')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por_boleta', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Departamentos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Municipios')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Ocupaciones')),
            ],
        ),
        migrations.CreateModel(
            name='BoletasConsejeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consejeria', models.CharField(blank=True, max_length=10, null=True)),
                ('periodicidad', models.IntegerField(blank=True, null=True)),
                ('nombre_persona_solicitante', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_consejero', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por_boleta_consejeria', to=settings.AUTH_USER_MODEL)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.Boletas')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por_boleta_consejeria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoletasConsejeriaPostPrueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consejeria', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_consejero', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por_boleta_postprueba', to=settings.AUTH_USER_MODEL)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.Boletas')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por_boleta_postprueba', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoletasObservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consejero', models.CharField(max_length=150)),
                ('observaciones', models.CharField(max_length=255)),
                ('tipo_observacion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por_boleta_obs', to=settings.AUTH_USER_MODEL)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.Boletas')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por_boleta_obs', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Establecimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
