# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletasPruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('numero_prueba', models.IntegerField(blank=True, null=True)),
                ('fecha_extraccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_muestra', models.DateTimeField(blank=True, null=True)),
                ('fecha_prueba', models.DateTimeField(blank=True, null=True)),
                ('kit_prueba_tamizaje', models.IntegerField(blank=True, null=True)),
                ('resultado_prueba_tamizaje', models.IntegerField(blank=True, null=True)),
                ('nombre_persona_prueba', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_prueba_confirmatoria', models.DateTimeField(blank=True, null=True)),
                ('kit_prueba_confirmatoria', models.IntegerField()),
                ('institucion_prueba_confirmatoria', models.IntegerField(blank=True, null=True)),
                ('resultado_prueba_confirmatoria', models.IntegerField(blank=True, null=True)),
                ('nombre_laboratorio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_refirio_prueba_confirmatoria', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizado_por_boleta_prueba', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='boletas',
            name='edad_anios',
            field=models.IntegerField(verbose_name='Anios'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='edad_meses',
            field=models.IntegerField(verbose_name='Meses'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='expediente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xfamero de Expediente Cl\xednico o C\xf3digo Identificador \xdanico:'),
        ),
        migrations.AddField(
            model_name='boletaspruebas',
            name='boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.Boletas'),
        ),
        migrations.AddField(
            model_name='boletaspruebas',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por_boleta_prueba', to=settings.AUTH_USER_MODEL),
        ),
    ]
