# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0003_auto_20160825_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaspruebas',
            name='kit_prueba_confirmatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_confirmatoria', to='general.Pruebas'),
        ),
        migrations.AlterField(
            model_name='boletaspruebas',
            name='kit_prueba_tamizaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_tamizaje', to='general.Pruebas'),
        ),
    ]
