# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0004_auto_20160825_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletasconsejeriapostprueba',
            name='referido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
