# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0005_boletasconsejeriapostprueba_referido'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletas',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletas',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletas',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletas',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
