# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0006_auto_20160825_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletas',
            name='otro_condicion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otra Condici\xf3n'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='actividad_economica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.ActividadesEconomicas', verbose_name='Actividad Econ\xf3mica'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boleta_origen_barrios', to='general.Ciudades', verbose_name='Barrio, Aldea, Colonia o Caserio'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle o Avenida'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='condiciones',
            field=models.ManyToManyField(to='boleta.Condiciones', verbose_name='Condici\xf3n (marque todas las que apliquen)'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='edad_anios',
            field=models.IntegerField(verbose_name='A\xf1os'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Soltero(a)'), (2, 'Casado(a)'), (3, 'Union Libre')], verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='grupo_etnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.GruposEtnicos', verbose_name='Grupo \xc9tnico'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N\xfamero de Casa o Apartamento'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='otro_grupo_etnico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro Grupo \xc9tnico'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Poblaciones', verbose_name='Poblaci\xf3n Solicitante'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Social'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='referencias',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Otras Referencias'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel\xe9fono Celular'),
        ),
        migrations.AlterField(
            model_name='boletas',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel\xe9fono Fijo'),
        ),
        migrations.AlterField(
            model_name='boletasconsejeria',
            name='fecha_consejeria',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Consejer\xeda Pre Prueba'),
        ),
        migrations.AlterField(
            model_name='boletasconsejeria',
            name='nombre_persona_solicitante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Persona Solicitante/Encargada/Responsable'),
        ),
    ]
