# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0010_auto_20160901_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletasclinicas',
            old_name='semanas_gestiacion',
            new_name='semanas_gestacion',
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='identificacion_genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True),
        ),
    ]
