# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0011_auto_20160901_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletasclinicas',
            name='blopsia',
        ),
        migrations.RemoveField(
            model_name='boletasclinicas',
            name='blopsia_fecha_realizacion',
        ),
        migrations.RemoveField(
            model_name='boletasclinicas',
            name='blopsia_ordenado_consulta',
        ),
        migrations.RemoveField(
            model_name='boletasclinicas',
            name='blopsia_resultado',
        ),
        migrations.AddField(
            model_name='boletasclinicas',
            name='biopsia',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletasclinicas',
            name='biopsia_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletasclinicas',
            name='biopsia_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='boletasclinicas',
            name='biopsia_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='caviral',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='caviral_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='caviral_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='caviral_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='cultivo',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='cultivo_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='cultivo_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='cultivo_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepb_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepb_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepb_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepc_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepc_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='hepc_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='lic4',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name='Linfocitos C4'),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='lic4_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='lic4_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='lic4_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='otro',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='otro_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='otro_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='otro_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='ppd',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='ppd_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='ppd_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='ppd_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rpr',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rpr_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rpr_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rpr_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rxtorax',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rxtorax_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rxtorax_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='rxtorax_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='sespu',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='sespu_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='sespu_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='sespu_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='usg',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='usg_fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='usg_ordenado_consulta',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'N/A')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='boletasclinicas',
            name='usg_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
    ]
