# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpn',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='rpn',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rpn',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
