# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160823_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
