# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_departamentos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsables',
            name='fecha_nacimiento',
            field=models.DateField(max_length=10),
        ),
    ]
